name: Dropdown Example

on:
  push:
    branches:
     - hemanth-feature
  workflow_dispatch:
    inputs:
      runner:
        description: "Select runner"
        required: true
        type: choice
        options:
          - linux
          - windows
          
      build-type:
        description: "Select Build-type"
        required: true
        type: choice
        options:
          - ecs-ci
          - ecs-cicd
          - ecs-promote
          - ecs-rollback
          - ec2-ci
          - ec2-cicd
          - ec2-promote
          - ec2-rollback
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print selected value
        run: echo "Environment is ${{ github.event.inputs.environment}}"
