name: Dropdown Example

on:
  push:
    branches:
     - hemanth-feature
  workflow_dispatch:
    inputs:
      runner:
        description: "Select runner"
        required: true
        type: choice
        options:
          - linux
          - windows
          
      build-type:
        description: "Select Build-type"
        required: true
        type: choice
        options:
          - ecs-ci
          - ecs-cicd
          - ecs-promote
          - ecs-rollback
          - ec2-ci
          - ec2-cicd
          - ec2-promote
          - ec2-rollback
jobs:
  run-job:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: print selected value
        run: |
          echo "Selected build type: ${{inputs.build-type}}"
          case "${{ inputs['build-type'] }}" in 
            ecs-ci)
            echo "Running ECS CI Proscess"
            ;;
            ecs-cicd)
            echo "Running ECS CI/CD Proscess"
            ;;
            ecs-promote)
            echo "Promoting ECS build"
            ;;
            ecs-rollback)
            echo "Rolling back ECS deployment"
            ;;
            *)
            echo "Invalid option selected"
          esac
            
